### ISSUE TITLE
Asterisk (*) should be a valid game end.

### ISSUE THREAD

**Issue by rooklift** [wfreeman/pgn#11]
From the PGN specs:

`The game termination marker is a symbol that is one of the following four values: "1-0" (White wins), "0-1" (Black wins), "1/2-1/2" (drawn game), and "*" (game in progress, result
unknown, or game abandoned).`

Currently it seems everything else is accepted, but not "*".

**Comment by freeeve** [comment]
Fixed in recent PR, thanks for the report!
