### ISSUE TITLE
En passant not working after loading board from FEN

### ISSUE THREAD

**Issue by fin0** [wfreeman/pgn#22]
When creating a new board from a FEN that contains an en passant, a capture is not possible. Instead, the error `ErrAttackerNotFound` is given.

This can be fixed by setting `Board.lastMove` in `NewBoardFEN()` with the respective pawn move if an en passant target square is part of the FEN.

Since I'm not sure if this is still maintained, just ping me if you would merge an existing PR, then I'll create one :)

**Comment by freeeve** [comment]
I am not actively working on it but I would merge a PR! Thanks!

**Comment by fin0** [comment]
Thanks, I created the PR. Will there be a new version after you merged it?
